import { IsString, IsOptional, IsIn, IsNumber, IsBoolean, IsArray, IsEnum, MaxLength } from 'class-validator';
import { ApiProperty } from '@nestjs/swagger';
import { PartialType } from '@nestjs/mapped-types';
import { RoutingProfile } from '../../routing/routing.types';
import { RouteStatus } from '../entities/route.entity';

export class CreateRouteDto {
  @IsIn(['bike', 'mtb', 'foot', 'car'])
  @ApiProperty({ description: 'Transport mode for the route.' })
  transport: RoutingProfile;

  @IsNumber()
  @ApiProperty({ description: 'Time available in minutes.' })
  timeAvailable: number;

  @IsBoolean()
  @IsOptional()
  @ApiProperty({ description: 'Whether the route returns to its start. Omitted means unknown.' })
  loop?: boolean;

  @IsArray()
  @IsString({ each: true })
  @IsOptional()
  @ApiProperty({ description: 'List of selected categories.' })
  selectedCategories?: string[];

  @IsString()
  @IsOptional()
  @MaxLength(200)
  @ApiProperty({ description: 'Custom route title. Default: autogenerated "Маршрут по {region} #N".' })
  title?: string;

  @IsString()
  @IsOptional()
  @MaxLength(2000)
  @ApiProperty({ description: 'Short description.' })
  description?: string;
}

export class UpdateRouteDto extends PartialType(CreateRouteDto) {
  @IsString()
  @IsOptional()
  @ApiProperty({ description: 'Custom route title.' })
  title?: string;

  @IsString()
  @IsOptional()
  @ApiProperty({ description: 'Short description.' })
  description?: string;

  @IsBoolean()
  @IsOptional()
  @ApiProperty({ description: 'Publish route to public.' })
  isPublished?: boolean;

  @IsEnum(RouteStatus)
  @IsOptional()
  @ApiProperty({ enum: RouteStatus })
  status?: RouteStatus;

  @IsBoolean()
  @IsOptional()
  @ApiProperty({ description: 'Mark as hidden.' })
  hidden?: boolean;
}